version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16.2
        # auth:
        #   username: mydockerhub-user
        #   password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.2
          docker_layer_caching: false

      - run:
          name: Build main service
          command: cd main ; make docker

      - run:
          name: Build admin service
          command: cd admin ; make docker

      - run:
          name: Build migration service
          command: cd db ; make docker

      - run:
          name: Run containers
          command: make docker_run && docker run --network lencse-link-test appropriate/curl --retry 100 --retry-connrefused http://admin:3000


    #   # build and push Docker image
    #   - run: |
    #       docker run -d --network container:my-app -v $(pwd)/.circleci/test:/usr/share/nginx/html:ro nginx:alpine
