version: 2.1
jobs:
  build:
    docker:
      - image: lencse/circleci-node-cypress:16.2
        environment:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
          ADMIN_PORT: 5001
          MAIN_PORT: 5000
          MAIN_URL: http://localhost:5000
          MAIN_INTERNAL_URL: http://localhost:5000
          DASHBOARD_PAGE_SIZE: 100
          JWT_SECRET: "My baby's got a secret"
          TERM: xterm

      - image: circleci/postgres:alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres

    steps:

      - checkout

      - run:
          name: Install dependecies for build and test
          command: make

      - run:
          name: Build main service
          command: cd main ; make

      - run:
          name: Test main service
          command: cd main ; make verify

      - run:
          name: Build admin service
          command: cd admin ; make

      - run:
          name: Test admin service
          command: cd admin ; make verify

      - run:
          name: Build migration service
          command: cd db ; make

      - run:
          name: Start servers
          command: make start
          background: true

      - run:
          name: Run database migrations
          command: make migrate

      - run:
          name: Load seed data
          command: make seed

      - run:
          name: Smoke test
          command: |
            sleep 5
            make smoke_test

      - run:
          name: E2E test
          command: node_modules/.bin/cypress run --browser chrome --headless

  images:
    docker:
      - image: cimg/base:2021.04

    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.2
          docker_layer_caching: false

      - run:
          name: Build main service
          command: cd main ; make docker

      - run:
          name: Build admin service
          command: cd admin ; make docker

      - run:
          name: Build migration service
          command: cd db ; make docker

      - run:
          name: Run containers
          command: make docker_run
          background: true

  deploy:
    docker:
      - image: cimg/base:2021.04

    steps:
      - checkout

      - run: echo Deploy

  build_circleci_docker:
    machine:
      image: "ubuntu-2004:202104-01"

    steps:
      - checkout

    #   - setup_remote_docker:
    #       version: 20.10.2
    #       docker_layer_caching: false

      - run:
          name: Build image
          command: docker build -t lencse/circleci-node-cypress:16.2 .circleci/docker

      - run:
          name: Test image
          command: docker run -it -v $(pwd)/.circleci/docker:/build lencse/circleci-node-cypress:16.2 /build/verify-cypress.sh


    #   # build and push Docker image
    #   - run: |
    #       docker run -d --network container:my-app -v $(pwd)/.circleci/test:/usr/share/nginx/html:ro nginx:alpine

workflows:
  version: 2

  default:
    jobs:
      - build
      - images:
          requires:
            - build
      - deploy:
          requires:
            - images

  circleci_docker:
    # triggers:
    #    - schedule:
    #        cron: "0 0 * * *"
    #        filters:
    #          branches:
    #            only:
    #              - main
    jobs:
      - build_circleci_docker
