version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.2
        environment:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
          ADMIN_PORT: 5001
          MAIN_PORT: 5000
          MAIN_URL: http://localhost:5000
          MAIN_INTERNAL_URL: http://localhost:5000
          DASHBOARD_PAGE_SIZE: 100
          JWT_SECRET: "My baby's got a secret"

      - image: circleci/postgres:alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres

    steps:
      - checkout

      - run:
          name: Install dependecies for build and test
          command: make

      - run:
          name: Build main service
          command: cd main ; make

      - run:
          name: Test main service
          command: cd main ; make verify

      - run:
          name: Build admin service
          command: cd admin ; make

      - run:
          name: Test admin service
          command: cd admin ; make verify

      - run:
          name: Build migration service
          command: cd db ; make

      - run:
          name: Start servers
          command: make start
          background: true

      - run:
          name: Run database migrations
          command: make migrate

      - run:
          name: Load seed data
          command: make seed

      - run:
          name: Smoke test
          command: |
            sleep 5
            make smoke_test

  images:
    docker:
      - image: cimg/base:2021.04

    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.2
          docker_layer_caching: false

      - run:
          name: Build main service
          command: cd main ; make docker

      - run:
          name: Build admin service
          command: cd admin ; make docker

      - run:
          name: Build migration service
          command: cd db ; make docker

      - run:
          name: Run containers
          command: make docker_run && docker run --network lencse-link-test appropriate/curl --retry 100 --retry-connrefused http://admin:3000
          background: true


    #   # build and push Docker image
    #   - run: |
    #       docker run -d --network container:my-app -v $(pwd)/.circleci/test:/usr/share/nginx/html:ro nginx:alpine

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
      - images:
          requires:
            - build
