import Head from 'next/head'
import { FunctionComponentFactory } from 'react'

export const Page: FunctionComponentFactory<{ title: string }> = ({ title, children }) => (
    <>
        <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <main className="font-sans">{children}</main>
    </>
)
