name: Node.js CI

on:
  push:
    branches:
      - main
      - deploy
  workflow_dispatch:

jobs:

  test:
    name: Test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SITE_URL: ${{ vars.SITE_URL }}
    permissions:
      actions: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Use NextJS cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Use Yarn cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      - name: Verify
        run: |
          make empty-url-data
          make verify
      - name: Setup git user
        uses: fregante/setup-git-user@v2
      - name: Publish to deploy branch
        run: |
          export LAST_COMMIT_MSG=`git log -1 --pretty=%B`
          git checkout --orphan deploy
          git commit -m "Deploy: $LAST_COMMIT_MSG"
          git push origin deploy --force

  wait_for_previous_deploy:
    name: Wait for previous deploy
    if: github.ref == 'refs/heads/deploy'
    runs-on: ubuntu-latest
    steps:
      - uses: mktcode/consecutive-workflow-action@eb43c6b5852dd0e33efa797a1817196d06daa4b2
        with:
          token: ${{ secrets.GH_TOKEN }}

  deploy:
    name: Deploy
    if: github.ref == 'refs/heads/deploy'
    needs:
      - wait_for_previous_deploy
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SITE_URL: ${{ vars.SITE_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Use NextJS cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Use Yarn cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      - name: Pull data from Google Sheets
        run: make src/data/urls.json
        env:
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
      - name: Build
        run: make
      - name: 'Deploy to Netlify'
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_DEPLOY_TOKEN }}
          NETLIFY_SITE_ID: ${{ vars.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true
          build_command: ':'
          install_command: ':'
          build_directory: 'out/'
